<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="microsoft.net.test.sdk" Version="18.6.0" />
    <PackageReference Include="nunit" Version="4.6.1" />
    <PackageReference Include="nunit3testadapter" Version="6.2.0" />
    <PackageReference Include="rebus.tests.contracts" Version="8.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rebus.AzureTables\Rebus.AzureTables.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="azure_storage_connection_string.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
